name: Build and deploy ASP.Net Core app to Azure Web App - OhunIslam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # ---- API ----
      - name: Restore API dependencies
        run: dotnet restore VoiceOfIslam.Api/VoiceOfIslam.Api.csproj

      - name: Publish API
        run: dotnet publish VoiceOfIslam.Api/VoiceOfIslam.Api.csproj --configuration Release --output ./publish-api

      # ---- WASM Client ----
      - name: Restore Client dependencies
        run: dotnet restore VoiceOfIslam.Client/VoiceOfIslam.Client.csproj

      - name: Publish Client
        run: dotnet publish VoiceOfIslam.Client/VoiceOfIslam.Client.csproj --configuration Release --output ./publish-client

      # ---- Merge Client into API ----
      - name: Copy WASM Client to API wwwroot
        run: |
          mkdir -p ./publish-api/wwwroot
          rm -rf ./publish-api/wwwroot/*
          cp -r ./publish-client/wwwroot/* ./publish-api/wwwroot/

      # ---- Upload artifact ----
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish-api


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58D3BD26411D47EA86F7C711203EEEEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFFFE1CF49B84A8BABD3906B728D42CA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7440CAA0269542CCA37A536757BF5994 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OhunIslam'
          slot-name: 'Production'
          package: .